export const projects = [
    {
        "id": "lp",
        "title": "Landmark Poster",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/lp/cover.png"),
        "details_img": "https://source.unsplash.com/random/700x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "next_project": "/design/project2",
        "speed": 2
    },
    {
        "id": "portfolio21",
        "title": "Personal Portfolio (2021 ver.)",
        "type_path": "webdev",
        "type": "web dev",
        "cover_img": require("../images/webdev/portfolio21/cover.png"),
        "details_img": "https://source.unsplash.com/random/500x1000",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project1",
        "next_project": "/design/project3",
        "speed": 2.5
    },
    {
        "id": "pantone",
        "title": "Pantone Book",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/pantone/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 4
    },
    {
        "id": "nonblue",
        "title": "Nonblue",
        "type_path": "uxui",
        "type": "children's book, UX/UI",
        "cover_img": require("../images/uxui/nonblue/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 2.5
    },
    {
        "id": "inscan",
        "title": "inScan",
        "type_path": "uxui",
        "type": "UX/UI",
        "cover_img": require("../images/uxui/inscan/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 4
    },
    {
        "id": "plastic2048",
        "title": "Plastic2048",
        "type_path": "webdev",
        "type": "web dev",
        "cover_img": require("../images/webdev/plastic2048/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 3
    },
    {
        "id": "portfolio22",
        "title": "This Very Portfolio",
        "type_path": "webdev",
        "type": "web dev",
        "cover_img": require("../images/webdev/portfolio22/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 4
    },
    {
        "id": "fromme",
        "title": "from: me",
        "type_path": "design",
        "type": "branding, graphic design",
        "cover_img": require("../images/design/fromme/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 2.5
    },
    {
        "id": "mfa",
        "title": "MFA Poster Series",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/mfa/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 4
    }, 
    {
        "id": "lostfound",
        "title": "Lost & Found",
        "type_path": "uxui",
        "type": "UX/UI",
        "cover_img": require("../images/uxui/lostfound/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 2
    },
    {
        "id": "typeposter",
        "title": "Typography Poster",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/typeposter/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 2
    },
    {
        "id": "infodesign",
        "title": "Information Design",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/infodesign/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 3
    },
    {
        "id": "remembering",
        "title": "Remembering",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/remembering/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 4
    },
    {
        "id": "serviceday",
        "title": "Service Day Project",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/serviceday/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 3
    },
    {
        "id": "bbg",
        "title": "Built By Girls x Speck Contest",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/bbg/cover.png"),
        "details_img": "https://source.unsplash.com/random/800x1200",
        "date": "Feb 2021",
        "tools": "Illustrator, HTML",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod. Aenean non nulla eleifend, viverra eros ac, pulvinar lacus. In enim lorem, elementum in posuere vitae, consectetur at metus. Donec ac nisi tortor.",
        "lesson": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec nibh nec ligula fringilla euismod.",
        "link": "for web dev projects",
        "prev_project": "/design/project2",
        "speed": 4
    },
]