export const projects = [
    {
        "id": "lp",
        "title": "Landmark Poster",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/lp/main.webp"),
        "main_img": require("../images/design/lp/main.webp"),
        "details_img": require("../images/design/lp/details.webp"),
        "date": "Feb 2021",
        "tools": "InDesign",
        "description": "a project where I was assigned a landmark in the history of design and asked to create a 15x30in poster with images and an essay about its significance. my subject was the sign program by Carbone Smolan Agency at Musée du Louvre.",
        "lesson": "always anchor elements to other things on the page, differentiating colors is a good way to distinguish elements at similar scales",
        "next_project": "/webdev/portfolio21",
        "speed": 2
    },
    {
        "id": "portfolio21",
        "title": "Personal Portfolio \n(2021 ver.)",
        "type_path": "webdev",
        "type": "web dev",
        "cover_img": require("../images/webdev/portfolio21/main.webp"),
        "main_img": require("../images/webdev/portfolio21/main.webp"),
        "details_img": require("../images/webdev/portfolio21/details.webp"),
        "date": "June 2021",
        "tools": "HTML, CSS, JS",
        "description": "my first ever portfolio! I created a prototype in Figma, built the entire website from scratch, and hosted it on GitHub Pages (now moved to netlify!).",
        "lesson": "how to use CSS Grid, how to position things (way harder than I thought...)",
        "link": "https://amazing-smakager-dd248d.netlify.app/",
        "prev_project": "/design/lp",
        "next_project": "/design/pantone",
        "speed": 2.5
    },
    {
        "id": "pantone",
        "title": "Pantone Book",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/pantone/cover.webp"),
        "main_img": require("../images/design/pantone/main.webp"),
        "details_img": require("../images/design/pantone/details1.webp"),
        "additional_img": require("../images/design/pantone/details2.webp"),
        "date": "May 2020",
        "tools": "Illustrator, InDesign",
        "description": "a project for a typography course where I was asked to create a book exploring 24 typefaces and 24 corresponding logotypes. I chose pantone as a theme since I liked the minimal design of Pantone chips!",
        "lesson": "how to create/use grid, how to create cohesive layout throughout an entire book",
        "prev_project": "/webdev/portfolio21",
        "next_project": "/uxui/nonblue",
        "speed": 4
    },
    {
        "id": "nonblue",
        "title": "Nonblue",
        "type_path": "uxui",
        "type": "UX/UI, children's book",
        "cover_img": require("../images/uxui/nonblue/main.webp"),
        "main_img": require("../images/uxui/nonblue/main.webp"),
        "details_img": require("../images/uxui/nonblue/details.webp"),
        "date": "Feb 2021",
        "tools": "Procreate, Figma",
        "description": "I wrote and illustrated a children's book called \"nonblue\" for my design capstone class. this web prototype is one of the deliverables for my project. you can read the book in the demo linked below!",
        "lesson": "how to write a children's story (e.g. what part of speech/verb tense to use, what pattern children find engaging), how to illustrate cartoon characters",
        "link": "https://www.figma.com/proto/ccrGGIY4sM6ZMLMCCxQb56/Nonblue?node-id=3%3A3&scaling=scale-down&page-id=0%3A1&starting-point-node-id=3%3A3",
        "prev_project": "/design/pantone",
        "next_project": "/uxui/inscan",
        "speed": 2.5
    },
    {
        "id": "inscan",
        "title": "inScan",
        "type_path": "uxui",
        "type": "UX/UI",
        "cover_img": require("../images/uxui/inscan/cover.webp"),
        "main_img": require("../images/uxui/inscan/main.webp"),
        "details_img": require("../images/uxui/inscan/details.webp"),
        "date": "Fall 2020",
        "tools": "Illustrator, Figma",
        "description": "a semester-long project where I was asked to design a solution to a unique problem in my life. I decided to design an app that would help people avoid allergens in food/medication since my siblings have allergies.",
        "lesson": "how to conduct interviews, benchmark against existing service, create personas, and define users' roles and goals, a bit about branding",
        "prev_project": "/uxui/nonblue",
        "next_project": "/webdev/plastic2048",
        "speed": 3.5
    },
    {
        "id": "plastic2048",
        "title": "Plastic2048",
        "type_path": "webdev",
        "type": "web dev",
        "cover_img": require("../images/webdev/plastic2048/main.webp"),
        "main_img": require("../images/webdev/plastic2048/main.webp"),
        "details_img": require("../images/webdev/plastic2048/details.webp"),
        "date": "April 2020",
        "tools": "HTML, CSS, JS",
        "description": "a final project where I was asked to produce a screen-based experience, preferably with interactivity. Plastic2048 was inspired by the game 2048, created by Gabriele Cirulli.",
        "lesson": "how to work with open source code, how games can convey messages in an engaging way",
        "link": "https://ne9th.github.io/plastic2048/",
        "prev_project": "/uxui/inscan",
        "next_project": "/webdev/portfolio22",
        "speed": 3
    },
    {
        "id": "portfolio22",
        "title": "Personal Portfolio \n(2022 ver.)",
        "type_path": "webdev",
        "type": "web dev",
        "cover_img": require("../images/webdev/portfolio22/cover.webp"),
        "main_img": require("../images/webdev/portfolio22/cover.webp"),
        "date": "Nov 2022",
        "tools": "HTML, CSS, JS, React, Bootstrap, Framer Motion ",
        "description": "since I've grown and learned so much after my first portfolio, I decided to create an entirely new website where I can showcase my current knowledge better. just like my old portfolio, this project started with a prototype in Figma.",
        "lesson": "how to use Framer Motion for animation, gained a better understanding of React amongst many many other lessons",
        "prev_project": "/design/plastic2048",
        "next_project": "/design/fromme",
        "speed": 4
    },
    {
        "id": "fromme",
        "title": "from: me",
        "type_path": "design",
        "type": "graphic design, branding",
        "cover_img": require("../images/design/fromme/main.webp"),
        "main_img": require("../images/design/fromme/main.webp"),
        "details_img": require("../images/design/fromme/details.webp"),
        "date": "June 2021",
        "tools": "InDesign",
        "description": "a brand identity and graphic guidelines for a made-up journaling company, from: me.",
        "lesson": "how to create brand identity, how to pivot when unexpected events happen",
        "prev_project": "/webdev/portfolio22",
        "next_project": "/design/mfa",
        "speed": 2.5
    },
    {
        "id": "mfa",
        "title": "MFA Poster Series",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/mfa/main.webp"),
        "main_img": require("../images/design/mfa/main.webp"),
        "details_img": require("../images/design/mfa/details.webp"),
        "additional_img": require("../images/design/mfa/mfa.gif"),
        "date": "Oct 2019",
        "tools": "InDesign, Illustration, Photoshop",
        "description": "a poster series inspired by an art piece from the Women Take the Floor exhibition at MFA Boston.",
        "lesson": "How to balance type with abstract elements, how to create GIFs",
        "prev_project": "/design/fromme",
        "next_project": "/uxui/lostfound",
        "speed": 4
    }, 
    {
        "id": "lostfound",
        "title": "Lost & Found",
        "type_path": "uxui",
        "type": "UX/UI",
        "cover_img": require("../images/uxui/lostfound/cover.webp"),
        "main_img": require("../images/uxui/lostfound/main.webp"),
        "details_img": require("../images/uxui/lostfound/details.webp"),
        "date": "April 2021",
        "tools": "Illustrator, Photoshop, Figma",
        "description": "a mobile prototype designed to help the elderly population locate their misplaced belongings. this project was designed with my grandma in mind!",
        "lesson": "how to design for elderly population or population who might not be tech-savvy",
        "prev_project": "/design/mfa",
        "next_project": "/design/typeposter",
        "speed": 2
    },
    {
        "id": "typeposter",
        "title": "Typography Poster",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/typeposter/main.webp"),
        "main_img": require("../images/design/typeposter/main.webp"),
        "details_img": require("../images/design/typeposter/details.webp"),
        "date": "July 2020",
        "tools": "Illustrator, InDesign",
        "description": "a typography project where I was asked to define and show examples of 21 typography terms, 28 letter form parts, 1 perfect set paragaph, and 1 paragraph with 5 common type inconsistences.",
        "lesson": "typography terms, how to work with complex layout",
        "prev_project": "/uxui/lostfound",
        "next_project": "/design/infodesign",
        "speed": 2
    },
    {
        "id": "infodesign",
        "title": "Infographic Poster",
        "type_path": "design",
        "type": "graphic design, information design",
        "cover_img": require("../images/design/infodesign/main.webp"),
        "main_img": require("../images/design/infodesign/main.webp"),
        "details_img": require("../images/design/infodesign/details.webp"),
        "date": "March 2021",
        "tools": "Illustrator, Photoshop, InDesign",
        "description": "an infographic poster where i was asked to tell 3 levels of story using 3 types of data techniques. I decided to go with isotype, map, and timeline.",
        "lesson": "how to go through complex data and present them in a way that's easy to understand",
        "prev_project": "/design/typeposter",
        "next_project": "/design/serviceday",
        "speed": 3
    },
    {
        "id": "serviceday",
        "title": "Service Day Project",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/serviceday/cover.webp"),
        "main_img": require("../images/design/serviceday/main.webp"),
        "details_img": require("../images/design/serviceday/details.webp"),
        "date": "May 2019",
        "tools": "Photoshop",
        "description": "a project for the 22nd Annual Service Day at Suffolk University. I was working as a graphic designer and had this amazing opportunity to design the entire project from poster to t-shirt!",
        "lesson": "how to use photoshop",
        "prev_project": "/design/infodesign",
        "next_project": "/design/bbg",
        "speed": 4
    },
    {
        "id": "bbg",
        "title": "Make My Case",
        "type_path": "design",
        "type": "graphic design",
        "cover_img": require("../images/design/bbg/cover.webp"),
        "main_img": require("../images/design/bbg/cover.webp"),
        "details_img": require("../images/design/bbg/details.webp"),
        "date": "June 2019",
        "tools": "Illustrator",
        "description": "a phone case design I submitted to Make My Case—a design contest held by BUILT BY GIRLS x Speck. Though I did not win, I had so much fun designing and exploring Illustrator for the first time!",
        "lesson": "how to use Illustrator",
        "prev_project": "/design/serviceday",
        "speed": 3
    },
]